### ISSUE TITLE
Totara 13+ regression - unable to install

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-local_maillog#12]
```
Totara 16.4 (Build: 20220826.00) command line installation program
Default exception handler: Table "config_plugins" does not exist Debug: 
Error code: ddltablenotexist
* line 727 of /lib/dml/moodle_database.php: dml_exception thrown
* line 1604 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 1850 of /lib/dml/moodle_database.php: call to moodle_database->get_records()
* line 1597 of /lib/moodlelib.php: call to moodle_database->get_records_menu()
* line 25 of /local/maillog/version.php: call to get_config()
* line 300 of /lib/classes/plugin_manager.php: call to include()
* line 330 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
* line 230 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
* line 156 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
* line 93 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
* line 390 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
* line 350 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
* line 741 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
* line 188 of /admin/cli/install_database.php: call to core_plugin_manager->all_plugins_ok()
```

Recent changes to version.php in particular with get_config calling is causing issues on install. I believe the code should be moved to upgrade.php instead and might fix the install issue.

https://github.com/catalyst/moodle-local_maillog/pull/10
https://github.com/catalyst/moodle-local_maillog/pull/11

@sumaiyamannan @danmarsden

**Comment by danmarsden** [comment]
they can't be moved to upgrade.php as it's not triggered in time with an incorrect version number.

**Comment by danmarsden** [comment]
I wonder if we should be adding an if !during_initial_install() into that chunk - because if it's during an install it won't have the old incorrect version number.

**Comment by danmarsden** [comment]
also note - T16 has a slightly different email_to_user function so we'll likely need a new branch for T16 support anyway.

**Comment by danmarsden** [comment]
should be sorted now - I've also pushed an untested T16 branch into the repo - use at your own risk (please test/let me know if it works...) - take note that the lib/moodlelib.php patch is also slightly different from the old one.
