### ISSUE TITLE
Version number for Totara branches is 11 chars as oppose to the usual 10.

### ISSUE THREAD

**Issue by LiamKearn** [catalyst/moodle-local_maillog#9]
Just a heads up here not a change request, happy to fork.

Have some tooling that depends on version numbers being able to parsed as a u32.

The version number for Totara is not a normal version and I'm surprised Totara has allows the installation of it in the first place.

Since it's since been incremented to `001` there is no 10 char version number that can be a smooth upgrade.

**Comment by danmarsden** [comment]
thanks for the report -  I'll create an internal WR and see if we can tidy this up so it doesn't bite us in future.

thanks!

**Comment by danmarsden** [comment]
Thanks @LiamKearn, @sumaiyamannan has just pushed a fix for this into the repos here now.

**Comment by LiamKearn** [comment]
Thanks @danmarsden @sumaiyamannan, Appreciate the assistance.
